from __future__ import absolute_import

from ._jitcode import (
		t, y,
		jitcode, jitcode_lyap, jitcode_restricted_lyap,
		provide_basic_symbols,
		ode_from_module_file,
		convert_to_required_symbols,
		)

try:
	from .version import version as __version__
except ImportError:
	from warnings import warn
	warn('Failed to find (autogenerated) version.py. Do not worry about this unless you really need to know the version.')
